grpc:
  server:
    port: 12345

server:
  port: 9090

envoy:
  admin:
    url: ${ENVOY_ADMIN_URL}
  listener:
    port: 8090

cluster:
  registry:
    cleanup-cron : "@daily"
  selector:
    refresh-cron: 0/20 * * * * *
    filter-out:
      - cache
      - xds_cluster

